site_name: Sqedule docs
site_url: https://docs.sqedule.io/

repo_name: fullstaq-labs
repo_url: https://github.com/fullstaq-labs/sqedule
edit_uri: edit/main/docs/

extra:
  latest_version: 0.1.0

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - macros

nav:
  - Home: index.md
  - User Guide:
    - Introduction: user_guide/index.md
    - Help & support: user_guide/help_support.md
    - Tutorials:
      - 1 Release audit logging: user_guide/tutorials/release-logging.md
      - 2 Release approval: user_guide/tutorials/approval.md
    - Concepts:
      - Applications & releases: user_guide/concepts/applications-releases.md
      - Versioning, proposals & reviews: user_guide/concepts/versioning.md
      - Approval rules: user_guide/concepts/approval-rules.md
      - Web interface: user_guide/concepts/web-interface.md
      - CLI: user_guide/concepts/cli.md
      - API: user_guide/concepts/api.md
    - Tasks:
      - Installing the CLI: user_guide/tasks/install-cli.md
      - Initial CLI setup: user_guide/tasks/initial-cli-setup.md
    - References:
      - API endpoints: user_guide/references/api-endpoints.md
      - CLI configuration: user_guide/references/cli-config.md
  - Server Guide:
    - Introduction: server_guide/index.md
    - Help & support: server_guide/help_support.md
    - Installation:
      - Requirements: server_guide/installation/requirements.md
      - With binary (no container): server_guide/installation/binary.md
      - With container: server_guide/installation/container.md
      - With Kubernetes: server_guide/installation/kubernetes.md
    - Configuration:
      - Ways to pass configuration: server_guide/config/ways.md
      - Naming format: server_guide/config/naming.md
      - Reference: server_guide/config/reference.md
      - PostgreSQL connection string: server_guide/config/postgresql.md
    - Concepts:
      - The Sqedule server executable: server_guide/concepts/server-exe.md
      - Security: server_guide/concepts/security.md
      - Database schema migration: server_guide/concepts/database-schema-migration.md
      - Multi-instance safety: server_guide/concepts/multi-instance-safety.md
    - Tasks:
      - Disabling automatic schema migration: server_guide/tasks/disabling-automatic-schema-migration.md
      - Manually migrating the database schema: server_guide/tasks/manual-database-schema-migration.md
      - Running multiple server instances: server_guide/tasks/multi-instance.md
  - About Fullstaq: fullstaq.md
