version: '3.5'

services:
  postgres:
    networks:
      - sqedule
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    networks:
      - sqedule
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  sqedule-webui:
    networks:
      - sqedule
    container_name: sqedule-webui
    environment:
      - NEXT_PUBLIC_API_SERVER_BASE_URL=http://localhost:3001
    image: node:15.14.0-alpine3.10
    command:
      - /bin/sh
      - '-c'
      - |
        set -ex
        cd /app
        npm install
        exec npm run dev
    volumes:
      - ../webui:/app:delegated
      - webui:/app/node_modules
    ports:
      - 3000:3000
    restart: unless-stopped

  sqedule-server:
    networks:
      - sqedule
    depends_on:
      - postgres
    container_name: sqedule-server
    image: sqedule-server:latest
    command: run --bind "" --db-type postgresql --db-connection 'dbname=${POSTGRES_USER:-postgres} user=${POSTGRES_USER:-postgres} password=${POSTGRES_PASSWORD:-changeme} host=postgres port=${POSTGRES_PORT:-5432}' --dev
    ports:
      - "3001:3001"
    restart: unless-stopped

networks:
  sqedule:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    webui:
