name: Docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yml
      - mkdocs.yml
      - requirements.mkdocs.txt
      - docs/**
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: venv
          key: docs-venv-${{ hashFiles('requirements-mkdocs.txt') }}
      - name: Create virtual environment
        run: python3 -m venv venv
      - run: ./venv/bin/pip install -U -r requirements-mkdocs.txt
      - run: ./venv/bin/mkdocs gh-deploy --force
